/**
 * SDS Compile BAML Command
 *
 * Reads capability.yaml for the current change and generates typed BAML function
 * stubs for each capability with baml_binding.auto_generate: true.
 *
 * Output: <change-dir>/generated/<FunctionName>.baml
 * Each file is marked with a DO NOT EDIT header — regenerate by re-running this command.
 */

import ora from 'ora';
import path from 'path';
import * as fs from 'fs';
import { parse as parseYaml } from 'yaml';
import { loadChangeContext } from '../../core/artifact-graph/index.js';
import { validateChangeExists } from './shared.js';
import {
  parseCapabilityYaml,
  normalizeField,
  type CapabilityYaml,
  type Field,
} from '../../core/capability/schema.js';

// -----------------------------------------------------------------------------
// Types
// -----------------------------------------------------------------------------

export interface CompileBamlOptions {
  change?: string;
  dryRun?: boolean;
  force?: boolean;
}

interface GeneratedStub {
  functionName: string;
  outputFile: string;
  content: string;
  skipped: boolean;
  skipReason?: string;
}

// -----------------------------------------------------------------------------
// BAML type mapping
// -----------------------------------------------------------------------------

/**
 * Map SDS field type strings to BAML type annotations.
 * BAML uses a TypeScript-like syntax but with specific type keywords.
 */
function toBamlType(typeStr: string): string {
  const normalized = typeStr.trim().toLowerCase();
  const map: Record<string, string> = {
    string: 'string',
    str: 'string',
    int: 'int',
    integer: 'int',
    float: 'float',
    number: 'float',
    bool: 'bool',
    boolean: 'bool',
    'list[string]': 'string[]',
    'list[int]': 'int[]',
    'record': 'map<string, string>',
  };

  if (map[normalized]) return map[normalized];

  // enum[...] → BAML union of string literals
  const enumMatch = typeStr.match(/^enum\[(.+)\]$/i);
  if (enumMatch) {
    const values = enumMatch[1].split(',').map((v) => `"${v.trim()}"`);
    return values.join(' | ');
  }

  // PascalCase → assumed to be a class/struct type — pass through
  if (/^[A-Z]/.test(typeStr)) return typeStr;

  // Default: pass through as-is
  return typeStr;
}

// -----------------------------------------------------------------------------
// BAML stub generator
// -----------------------------------------------------------------------------

function normalizeFields(fields: Field[]) {
  return fields.map(normalizeField);
}

function buildBamlStub(cap: CapabilityYaml): string {
  const fn = cap.baml_binding!.function;
  const inputs = normalizeFields(cap.inputs);
  const outputs = normalizeFields(cap.outputs);

  // Build class definitions for inputs and outputs if there are named fields
  const inputClassName = `${fn}Input`;
  const outputClassName = `${fn}Output`;

  const inputFields = inputs
    .map((f) => `  ${f.name} ${toBamlType(f.type)}${f.required ? '' : '?'}`)
    .join('\n');

  const outputFields = outputs
    .map((f) => `  ${f.name} ${toBamlType(f.type)}${f.required ? '' : '?'}`)
    .join('\n');

  const preconditionComments = cap.preconditions
    .map((p) => `  // PRECONDITION: ${p}`)
    .join('\n');

  const guaranteeComments = cap.guarantees
    .map((g) => `  // GUARANTEE: ${g}`)
    .join('\n');

  const effectsComments = [
    `  // effects.reversible:         ${cap.effects.reversible}`,
    `  // effects.external:           ${cap.effects.external}`,
    `  // effects.idempotent:         ${cap.effects.idempotent}`,
    `  // effects.produces_evidence:  ${cap.effects.produces_evidence}`,
  ].join('\n');

  const composabilityComments = [
    cap.composability.requires_before.length > 0
      ? `  // requires_before: ${cap.composability.requires_before.join(', ')}`
      : null,
    cap.composability.requires_after.length > 0
      ? `  // requires_after:  ${cap.composability.requires_after.join(', ')}`
      : null,
    cap.composability.conflicts_with.length > 0
      ? `  // conflicts_with:  ${cap.composability.conflicts_with.join(', ')}`
      : null,
  ]
    .filter(Boolean)
    .join('\n');

  const lines: string[] = [
    `// Auto-generated by /sds:compile-baml from capability.yaml — DO NOT EDIT`,
    `// capability: ${cap.id}  version: ${cap.version}`,
    `// Regenerate: openspec sds compile-baml`,
    ``,
  ];

  // Input class
  if (inputs.length > 0) {
    lines.push(`class ${inputClassName} {`);
    lines.push(inputFields);
    lines.push(`}`);
    lines.push(``);
  }

  // Output class
  if (outputs.length > 0) {
    lines.push(`class ${outputClassName} {`);
    lines.push(outputFields);
    lines.push(`}`);
    lines.push(``);
  }

  // Function stub
  const inputParam =
    inputs.length > 0 ? `input ${inputClassName}` : '';
  const outputType = outputs.length > 0 ? outputClassName : 'string';

  lines.push(`function ${fn}(${inputParam}) -> ${outputType} {`);
  lines.push(`  client "openai/gpt-4o"  // TODO: replace with target model`);
  lines.push(`  prompt #"`);
  lines.push(`    ${cap.description.trim()}`);
  lines.push(`    `);

  if (preconditionComments) {
    lines.push(preconditionComments);
  }
  if (guaranteeComments) {
    lines.push(guaranteeComments);
  }
  if (effectsComments) {
    lines.push(effectsComments);
  }
  if (composabilityComments) {
    lines.push(composabilityComments);
  }

  if (inputs.length > 0) {
    lines.push(`    `);
    lines.push(`    Input:`);
    inputs.forEach((f) => lines.push(`    {{ input.${f.name} }}`));
  }

  lines.push(`  "#`);
  lines.push(`}`);
  lines.push(``);

  // Test block if test_inputs provided
  if (cap.baml_binding?.test_inputs && cap.baml_binding.test_inputs.length > 0) {
    lines.push(`test ${fn}Test {`);
    lines.push(`  functions [${fn}]`);
    lines.push(`  args {`);
    const firstInput = cap.baml_binding.test_inputs[0];
    for (const [key, val] of Object.entries(firstInput)) {
      const valStr = typeof val === 'string' ? `"${val}"` : String(val);
      lines.push(`    ${key} ${valStr}`);
    }
    lines.push(`  }`);
    lines.push(`}`);
    lines.push(``);
  }

  return lines.join('\n');
}

// -----------------------------------------------------------------------------
// Command Implementation
// -----------------------------------------------------------------------------

export async function sdsCompileBamlCommand(options: CompileBamlOptions): Promise<void> {
  const spinner = ora('Reading capability.yaml...').start();

  try {
    const projectRoot = process.cwd();
    const changeName = await validateChangeExists(options.change, projectRoot);
    const context = loadChangeContext(projectRoot, changeName);
    if (!context.schemaName.startsWith('sds-governed')) {
      spinner.warn(`compile-baml is intended for governed-tier changes (schema: ${context.schemaName}).`);
      console.log(`Proceeding anyway — no capability.yaml may be present.`);
    }
    const changeDir = path.join(projectRoot, 'openspec', 'changes', changeName);
    const capabilityPath = path.join(changeDir, 'capability.yaml');

    if (!fs.existsSync(capabilityPath)) {
      spinner.fail(`capability.yaml not found at: openspec/changes/${changeName}/capability.yaml`);
      throw new Error(
        `capability.yaml is required for /sds:compile-baml.\n` +
          `Run 'openspec instructions capability' to create it.`
      );
    }

    const raw = parseYaml(fs.readFileSync(capabilityPath, 'utf-8'));
    const capability = parseCapabilityYaml(raw);

    // Check whether BAML binding is configured
    if (!capability.baml_binding) {
      spinner.warn(`No baml_binding defined in capability.yaml — nothing to generate.`);
      console.log(`Add a baml_binding block to capability.yaml to enable stub generation.`);
      return;
    }

    if (!capability.baml_binding.auto_generate) {
      spinner.info(
        `baml_binding.auto_generate is false — skipping stub generation for ${capability.baml_binding.function}.`
      );
      console.log(`Set auto_generate: true in capability.yaml to generate a stub.`);
      return;
    }

    const generatedDir = path.join(changeDir, 'generated');
    const stub = buildBamlStub(capability);
    const outFile = `${capability.baml_binding.function}.baml`;
    const outPath = path.join(generatedDir, outFile);

    const result: GeneratedStub = {
      functionName: capability.baml_binding.function,
      outputFile: `openspec/changes/${changeName}/generated/${outFile}`,
      content: stub,
      skipped: false,
    };

    if (!options.force && fs.existsSync(outPath)) {
      result.skipped = true;
      result.skipReason = 'File already exists (use --force to overwrite)';
    }

    spinner.stop();

    if (options.dryRun) {
      console.log(`[dry-run] Would write: ${result.outputFile}`);
      console.log('\n--- BAML stub preview ---');
      console.log(stub);
      return;
    }

    if (result.skipped) {
      console.log(`Skipped: ${result.outputFile} (${result.skipReason})`);
      return;
    }

    if (!fs.existsSync(generatedDir)) {
      fs.mkdirSync(generatedDir, { recursive: true });
    }

    fs.writeFileSync(outPath, stub, 'utf-8');
    console.log(`Generated: ${result.outputFile}`);
    console.log(`\nNext steps:`);
    console.log(`  1. Review and customize the prompt in ${outFile}`);
    console.log(`  2. Replace "openai/gpt-4o" with your target model`);
    console.log(`  3. Run 'openspec sds check-drift' after wiring to a live BAML runtime`);
  } catch (error) {
    spinner.fail('compile-baml failed');
    throw error;
  }
}
